name: Docker Image CI

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file "Portfolio_Website/Dockerfile" --tag portfolio_website:$(date +%s)
